minimal_mistakes_skin: "plum"

locale: "ko-KR"
title: "sso312.com"
title_separator: "&#124;"
name: "sso312"
description: "Oracle DBA / DB Engineer"
url: "https://sso312.github.io"
baseurl: ""
repository: "sso312/sso312.github.io"
search: true
search_full_content: true

# 댓글 기능은 사용하지 않는다.
comments:
  provider: false

author:
  name: "sso312"
  bio: "Oracle DBA / DB Engineer"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sso312"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sso312"

include:
  - _pages

exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - screenshot-layouts.png
  - screenshot.png
  - staticman.yml
  - vendor

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "Asia/Seoul"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      comments: false
      related: true
      sidebar:
        nav: "categories"
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
      sidebar:
        nav: "categories"
